name: "Dev Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 543c2581-dd7f-406f-b108-ec59940a932c
          tenant-id: 964c8d5d-5d50-4ef0-8220-dd646a5be85e
          subscription-id: d6648ae8-3690-454e-ab03-88b9b87483d3
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev    
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 543c2581-dd7f-406f-b108-ec59940a932c
          tenant-id: 964c8d5d-5d50-4ef0-8220-dd646a5be85e
          subscription-id: d6648ae8-3690-454e-ab03-88b9b87483d3
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev              
          
